tap "argon/mas"
tap "browsh-org/browsh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "jesseduffield/lazygit"
tap "rcmdnk/file"
tap "teamookla/speedtest"
brew "antigen"
brew "bash-completion"
brew "bat"
brew "fontconfig"
brew "cmake"
brew "cocoapods"
brew "coreutils"
brew "deno"
brew "exa"
brew "gobject-introspection"
brew "libass"
brew "libbluray"
brew "tesseract"
brew "ffmpeg"
brew "fish"
brew "gcc"
brew "gh"
brew "git"
brew "imagemagick"
brew "jpegoptim"
brew "libidn"
brew "llvm"
brew "mas"
brew "mecab"
brew "mysql"
brew "neofetch"
brew "nodebrew"
brew "openjdk"
brew "optipng"
brew "pandoc"
brew "pngquant"
brew "postgresql"
brew "procs"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ruby"
brew "sbt"
brew "swig"
brew "tmux"
brew "tree"
brew "vim"
brew "w3m"
brew "watchman"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zplug"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "heroku/brew/heroku"
brew "jesseduffield/lazygit/lazygit"
brew "rcmdnk/file/brew-file"
brew "teamookla/speedtest/speedtest"
cask "alfred"
cask "amazon-photos"
cask "app-cleaner"
cask "biscuit"
cask "bitwarden"
cask "blender"
cask "brave-browser"
cask "clipy"
cask "dash"
cask "deepl"
cask "discord"
cask "docker"
cask "firefox"
cask "firefox-developer-edition"
cask "google-chrome-canary"
cask "google-earth-pro"
cask "google-japanese-ime"
cask "google-trends"
cask "google-web-designer"
cask "hyper"
cask "icons8"
cask "imageoptim"
cask "imazing"
cask "iterm2"
cask "karabiner-elements"
cask "keka"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "notion"
cask "numi"
cask "postman"
cask "spotify"
cask "swimat"
cask "ticktick"
cask "unity-hub"
cask "visual-studio-code"
cask "xquartz"
mas "1440", id: 1483764819
mas "Bandwidth+", id: 490461369
mas "BetterSnapTool", id: 417375580
mas "DaisyDisk", id: 411643860
mas "DevCleaner", id: 1388020431
mas "Developer", id: 640199958
mas "Disk Speed Test", id: 425264550
mas "Endel", id: 1484348796
mas "Evernote", id: 406056744
mas "GoodNotes", id: 1444383602
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Playgrounds", id: 1496833156
mas "RunCat", id: 1429033973
mas "Shazam", id: 897118787
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Speedtest", id: 1153157709
mas "The Unarchiver", id: 425424353
mas "TweetDeck", id: 485812721
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
