gui:
  # stuff relating to the UI
  language: "auto" # one of 'auto' | 'en' | 'zh' | 'pl' | 'nl' | 'ja' | 'ko'
  timeFormat: "2006/01/02 15:04:05 +0900 JST" # https://pkg.go.dev/time#Time.Format
os:
  editCommand: "" # see 'Configuring File Editing' section
  editCommandTemplate: ""
  openCommand: ""
refresher:
  refreshInterval: 10 # File/submodule refresh interval in seconds. Auto-refresh can be disabled via option 'git.autoRefresh'.
  fetchInterval: 60 # Re-fetch interval in seconds. Auto-fetch can be disabled via option 'git.autoFetch'.
update:
  method: prompt # can be: prompt | background | never
  days: 14 # how often an update is checked for
reporting: "undetermined" # one of: 'on' | 'off' | 'undetermined'
# determines whether hitting 'esc' will quit the application when there is nothing to cancel/close
promptToReturnFromSubprocess: true # display confirmation when subprocess terminates
keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>" # alternative/alias of quit
    return: "<c-q>" # return to previous menu, will quit if there's nowhere to return
    quitWithoutChangingDirectory: "Q"
customCommands:
  - key: "<c-r>"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"
  - key: "O"
    context: "files"
    command: "oco"
    description: "commit with AI"
    loadingText: "opening ai commit tool(oco)"
    output: terminal
  - key: "V" # couldn't think of a better keybinding
    prompts:
      - type: "input"
        title: "PR id:"
    command: "hub pr checkout {{index .PromptResponses 0}}"
    context: "localBranches"
    loadingText: "checking out PR"
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
